### ISSUE TITLE
ValueText uses incorrect types

### ISSUE THREAD

**Issue by ZebraFlesh** [ericnewton76/gmaps-api-net#106]
`ValueText` uses a `string` type for the `Value` property.  Looking at the [Google Maps docs](https://developers.google.com/maps/documentation/distance-matrix/intro#DistanceMatrixResponses), the response for value is some kind of number. This is corroborated by their own [Javascript API documentation](https://developers.google.com/maps/documentation/javascript/3.exp/reference#Distance). Digging deeper, Google's Java client implementation exposes value as a Java long in both the [Distance class](https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/model/Distance.java#L25) and the [Duration class](https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/model/Duration.java#L25). This is equivalent to an [Int64 in C#](https://msdn.microsoft.com/en-us/library/ms228360(v=vs.90).aspx).

So it seems like the definition of `ValueText` should be changed to:
```
public class ValueText
  {
    [JsonProperty("value")]
    public Int64 Value { get; set; }

    [JsonProperty("text")]
    public string Text { get; set; }

    public override string ToString()
    {
      return String.Format("{0} ({1})", Text, Value);
    }
}
```

**Comment by richardthombs** [comment]
Thanks for the heads up, @ZebraFlesh.

**Comment by ericnewton76** [comment]
Because this would be technically an interface breaking change, maybe we do this prior to v1.0 ?

**Comment by ericnewton76** [comment]
Okay, so I implemented this in commit 82a0bad.  I'm wondering about since it was string before it could be empty, whereas now its a long and if the json data is empty, it'll have to use 0, which might be not correct.

**Comment by ZebraFlesh** [comment]
I think it will be correct from Google's perspective, but might cause issues for consumers who made incorrect assumptions.

It's been a while since I've looked at this. Where is `ValueText` used? Is it just distance and duration representations, or does this class see wider usage?

**Comment by ericnewton76** [comment]
Here's the code map image:
![image](https://user-images.githubusercontent.com/2211788/31863954-86b54d94-b723-11e7-9235-a4f1f3babbe9.png)

Basically used:
- Direction API for DirectionLeg and DirectionStep
- Distance Matrix for distance / duration

**Comment by ZebraFlesh** [comment]
Thanks. That seems like using 0 would be correct (since it's all distance/duration).
