### ISSUE TITLE
Street View Image API

### ISSUE THREAD

**Issue by connorb09** [ericnewton76/gmaps-api-net#107]
This is a very useful library and has tidied up my code significantly. Just wondered if there are any plans to add support for the Street View Image API?

**Comment by ericnewton76** [comment]
Would be great for you to do some implementation and submit as a pull request.  Try to include some unit testing on how it builds the url and so forth and we'll get it integrated in asap!

Any contributions are welcome and appreciated

**Comment by ericnewton76** [comment]
Working on this in my branch, streetviewapi

**Comment by ericnewton76** [comment]
Implemented via PR #111
