### ISSUE TITLE
Proxy blocking application

### ISSUE THREAD

**Issue by refreshlearn** [ericnewton76/gmaps-api-net#127]
The application is getting blocked due to proxy when tried to search a location. Is there a solution for this?

**Comment by ericnewton76** [comment]
You can configure a proxy via the Application's web/app config file.

For more info, see this article: https://docs.microsoft.com/en-us/dotnet/framework/network-programming/proxy-configuration#static-proxies

There could be a use case for directly specifying the proxy specifically for these calls, which we dont have any support for atm.
