### ISSUE TITLE
Google Namespace

### ISSUE THREAD

**Issue by ppumkin** [ericnewton76/gmaps-api-net#13]
You should consider changing the namespace from Google to your own. If this project gets big tracktion (which it already has some) Google will be on your backside for using their name on something that is not theirs.

You should use the Projects name  or codename as the base Namespace then you can expand to Google.  As it stands it looks like the project was created and belongs to google - Say somebody else looked at the project without realising it was installed from this source.

Also - It is prohibited top use the API without displaying their map. You need to make that clear as it can get people into trouble.

I don't work for Google - I just see a licensing issue here and wanted to warn you guys about potential problems. 

Otherwise great job!

**Comment by richardthombs** [comment]
We've decided to keep the "Google" namespace for now.

@mieliespoor I think Google have changed their logo requirements, or at least the link you provided doesn't mention them anymore. But even if a logo is still required, it's the responsibility of whoever consumes this library to make sure they are following Google's requirements, not ours.

**Comment by mieliespoor** [comment]
@richardthombs I agree with the call to keep the Google namespace. It would be a real pain to change that and all dependant applications.

I think I was merely mentioning that it is up to the consumer of this library to comply with the requirements from Google.
