### ISSUE TITLE
You are trying to install this package into a project that targets '.NETFramework,Version=v4.5

### ISSUE THREAD

**Issue by pavelgronsky** [ericnewton76/gmaps-api-net#137]
Hello. When I try to install package by Oackage Manager Console, than I take error:

Install-Package : Could not install package 'gmaps-api-net 0.24.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For  more information, contact the package author.

**Comment by ericnewton76** [comment]
We target NetStandard1.3 which is minimum NetFramework of 4.6

https://docs.microsoft.com/en-us/dotnet/standard/net-standard
