### ISSUE TITLE
Api key usage in VB.net

### ISSUE THREAD

**Issue by sumisoso** [ericnewton76/gmaps-api-net#22]
I'm having difficulty implementing the usage of an API key.
currently using version: 0.11.1.0 (nuget package)

My project is VB.NET and I'm trying to add my API key with the following code recommended by the README:

`GoogleSigned.AssignAllServices(new GoogleSigned("API_key"));`

I am very new to programming and this is the first package I have used. 

I have attempted a number of things, but first the pertinent code:

```
Dim apikey As GoogleSigned
Dim address As String = "1600 Amphitheatre Parkway Mountain View, CA 94043"
Dim geoCode As New GeocodingRequest
Dim geoResponse As New GeocodeResponse
Dim latitude As Double
Dim longitude As Double

geoCode.Address = address
geoCode.Senson = "false"
'following fails --- error: Argument Not specified  for parameter 'usablePrivateKey'
apikey = GoogleSigned.AssignAllServices(new GoogleSigned("API_key_here")
'also fails --- error: Argument Not specified  for parameter 'usablePrivateKey'
GoogleSigned.AssignAllServices(new GoogleSigned("API_key_here"))
'I have attempted to add the second parameter, switched parameter placements
'with no success.
geoResponse = New GeocodingService().GetResponse(geoCode)

If geoResponse.Results.Count > 1 Then
    latitude = geoResponse.Results(0).Geometry.Location.Latitude
    longitude = geoResponse.Results(0).Geometry.Location.Longitude
Else 'returned only 1 result
    latitude = geoResponse.Results.Single().Geometry.Location.Latitude
    longitude = geoResponse.Results.Single().Geometry.Location.Longitude
End If

'then save the values to a database for use without re-querying google for the latitude and longitude
```

I am able to get the latitude and longitude without the API key but am limited to the number of searches per 24 hours.

After reading the issues already posted I believe I need to have GoogleSignedType.Apikey in order for this to function where the default appears to be GoogleSignedType.Business, or this is not available with the version I am using, any help would be appreciated.

**Comment by richardthombs** [comment]
Hi @sumisoso , I'm hoping that 3 years later, you have managed to solve this problem or worked around it, so I'm going to close the issue.
