### ISSUE TITLE
localized geocoding result

### ISSUE THREAD

**Issue by faridcher** [ericnewton76/gmaps-api-net#26]
Thanks for the great api. 
How can I get the localized result from google geocoding result with this api?

for example:
English(Default):
http://maps.google.com/maps/api/geocode/xml?address=jerusalem&sensor=false
Hebrew:
http://maps.google.com/maps/api/geocode/xml?address=jerusalem&sensor=false&language=he

Thanks

**Comment by faridcher** [comment]
I got it. I should set the GeocodingRequest.Language property .
Thanks

**Comment by ericnewton76** [comment]
Exactly.. :+1:
