### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by chiptus** [ericnewton76/gmaps-api-net#28]
This is a great job you've done.
Is there a plan to provide a more verbose documentation for this api?

**Comment by Sheepzez** [comment]
I agree that this project is in need of more detailed documention. 

@ericnewton76 what do you think of using GitHub's Wiki feature for extended documentation pages?

**Comment by Sheepzez** [comment]
I've created the wiki at https://github.com/ericnewton76/gmaps-api-net/wiki and added a couple initial pages. Hopefully over time we can add much more detailed documentation for this project.

**Comment by ericnewton76** [comment]
That would be great.  Thanks for the contributions
