### ISSUE TITLE
Do I use WayPoint or Location?

### ISSUE THREAD

**Issue by migig** [ericnewton76/gmaps-api-net#29]
Using `WayPoint` triggers an obsolete warning: `Functionality was absorbed by Location being polymorphic`.

But all the library's functions expect `WayPoint` as arguments, not `Location`.

So what do I do to get rid of these warnings?

**Comment by xxCruciblexx** [comment]
I'm having the same concern. Does anyone have any input on this?

**Comment by ericnewton76** [comment]
What library functions are you using that only accept Waypoint?  Those probably need to be updated to use the more generic Location type.

**Comment by Sheepzez** [comment]
Hi, I saw this issue hanging open and I think I can contribute.

It seems that the DistanceMatrixRequest.AddOrigin method, and DistanceMatrixRequest.AddDestination only accept Waypoint objects as parameters.

There doesn't appear to be any Location overloads.

**Comment by redrails** [comment]
I know this is an old issue but I'm wondering how `Location` can be used to replace `Waypoint`. I am trying to set two points to compare distances between them and as the wiki [suggests](https://github.com/ericnewton76/gmaps-api-net/wiki/API:-Distance-Matrix), I should use `Waypoint` however that is now obsolete.

`Location` doesn't seem to take a `Longitude` and `Latitude`, so what is the correct way to set two points and find a distance?

**Comment by richardthombs** [comment]
@migig To answer your original question, you use `Location` and `LatLng`, not `Waypoint`, which is obsolete.

@redrails `LatLng` is derived from `Location`, so you can use a `LatLng` wherever you would use a `Location`.

Eg:

```c#
maxtrixRequest.AddOrigin(new LatLng(28.452694, -80.979195));
```
