### ISSUE TITLE
Compatibility with Windows Phone ?

### ISSUE THREAD

**Issue by suzand** [ericnewton76/gmaps-api-net#31]
Hello, I tried to install gmaps-api-net 0.12.118 and it fails
I'm new to Windows Phone 8.1 development and I don't know if it is possible to adapt the package.
- Is there a way to make it compatible with Windows Phone 8.1 ?
- Is anyone planing to do it ?

Regards 

```
Install failed. Rolling back...
Install-Package : Could not install package 'gmaps-api-net 0.12.118'. You are trying to install this package into a project that targets '.NETCore,Version=v4.5.1', but the 
package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package gmaps-api-net
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

PM> 
```

**Comment by casaout** [comment]
*push* Is it right, that the library is not compatible with Windows Phone? Thanks.

**Comment by ericnewton76** [comment]
Currently I believe its not Windows phone compatible becausae of the different set of core .net libraries that Windows phone provides.

Theres additionally work (Issue #57) to make it work under several platforms but this type of request is a big time sink.

**Comment by ericnewton76** [comment]
I think this effectively duplicates Issue #59

**Comment by richardthombs** [comment]
We support .NET 4.61 and .NET Standard 1.3. I can see that Windows Phone requires .NET Standard 1.2, so unless .NET 4.61 will work on the phone, I think you are out of luck.
