### ISSUE TITLE
Sensor parameter still required

### ISSUE THREAD

**Issue by Sheepzez** [ericnewton76/gmaps-api-net#32]
I noticed that in a couple of the request objects the sensor parameter is required, one example is the DistanceMatrixRequest.

The code that ensures the sensor is here https://github.com/ericnewton76/gmaps-api-net/blob/master/src/Google.Maps/DistanceMatrix/DistanceMatrixRequest.cs#L166

But as your can see (here)[https://developers.google.com/maps/documentation/distancematrix/intro#Sensor] the DistanceMatrix API no longer requires this.

I could submit a pull-request to fix this bug if that is desirable? Or someone already involved in the project could.

**Comment by richardthombs** [comment]
I've never understood the point of the sensor parameter, if it works without it, then please submit a PR and we'll lose it.

**Comment by Sheepzez** [comment]
I'd be happy to add this fix in, but I'll wait to start the implementation until the Places pull-request is in, and the Time Zone one after that. Don't want to make merging a nightmare :)

**Comment by richardthombs** [comment]
I think the time is right to do this - @Sheepzez do you still want to make the change? If not I'm happy to.

**Comment by Sheepzez** [comment]
@richardthombs I've got a few other projects on my plate at the moment, so you go ahead and do it :) Thanks.

**Comment by richardthombs** [comment]
#83 removes the Sensor parameter
