### ISSUE TITLE
Places Details?

### ISSUE THREAD

**Issue by kijanawoodard** [ericnewton76/gmaps-api-net#36]
I may have overlooked it, but I'm not seeing a way to access Places Details: https://developers.google.com/places/web-service/details

**Comment by Sheepzez** [comment]
You are correct in thinking that it's not implemented. Only the basic Places API stuff is there.

I'll try and see if I can implement the rest of the Places API (including Details) and submit a pull request in the next week or so (If schedule permits).

Thanks for making an issue!
