### ISSUE TITLE
No way to specify the API Key

### ISSUE THREAD

**Issue by vishnoor** [ericnewton76/gmaps-api-net#40]
Please provide a property on the GeoCodingRequest class so that one can specify the API key. 
https://developers.google.com/maps/documentation/geocoding/get-api-key#key

**Comment by Sheepzez** [comment]
Hi @vishnoor,

You can specify an API key using the GoogleSigned class. I have copied an example below from the readme.

```
GoogleSigned.AssignAllServices(new GoogleSigned("your-api-key"));
// Then do as many requests as you like...
var request = new GeocodingRequest { Address="1600 Amphitheatre Parkway", Sensor = false };
var response = GeocodingService.GetResponse(request);
```

**Comment by vishnoor** [comment]
Hi @Sheepzez ,
   I keep getting a RequestDenied status in the response. I am not using a paid version of the API but rather the free one with a 2500 request per day limit. Will fiddler and see if the API key is indeed being appended. Thanks for the code bit.

**Comment by bbotond90** [comment]
It is because you are using http instead of https. I have a pull request on it.

**Comment by richardthombs** [comment]
@bbotond90 FYI, your pull request appears to only fix the distance matrix API, not the Geocoding API

**Comment by bbotond90** [comment]
FYI, you are right, but that is the same problem. It is easy to fix :)

**Comment by ericnewton76** [comment]
For historical purposes this was Pull Request #64
