### ISSUE TITLE
Geocoded waypoints missing from DirectionResponse

### ISSUE THREAD

**Issue by Maetiz** [ericnewton76/gmaps-api-net#49]
The response JSON includes the array 'geocoded_waypoints' which is not implemented in the DirectionResponse.

A geocoded waypoint includes the information of whether or not the queried locations in the request were matched accurately or partially (field: partial_match).

I already added the new class and added unit tests for it. I also added a few status codes missing from the enum.
https://github.com/Maetiz/gmaps-api-net

**Comment by ericnewton76** [comment]
Hey, go ahead and create a pull request and we'll look at it.
