### ISSUE TITLE
Polylines in Static Map

### ISSUE THREAD

**Issue by chriser-** [ericnewton76/gmaps-api-net#50]
At the moment, it is not possible to add a polyline path directly to a static map request.
You can construct a polyline by points (list of lat/lng) and setting `Path.Encode = true`, but you cannot directly set a polyline.
I tried implementing it quickly by myself but ended up with an `UriFormatException` (however the link generated works in the browser)

https://developers.google.com/maps/documentation/static-maps/intro#EncodedPolylines

**Comment by ericnewton76** [comment]
Lets see your pull request, maybe we can resolve the UriException

**Comment by ericnewton76** [comment]
Did you try the Path or Paths properties on StaticMapRequest ?  

These provide a way to construct a polyline and apply it to the StaticMapRequest you are about to send into the gmaps api...
