### ISSUE TITLE
Distance Matrix getting REQUEST_REQUEST

### ISSUE THREAD

**Issue by obito1406** [ericnewton76/gmaps-api-net#53]
So when i tried;
`           Waypoint startPoint = new Waypoint(49.171020M, 5.969358M);
            Waypoint endPoint = new Waypoint(54.555393M, 23.362615M);

```
        SortedList<int, Waypoint> originWayPoint = new SortedList<int, Waypoint>();
        SortedList<int, Waypoint> destinyWayPoint = new SortedList<int, Waypoint>();

        originWayPoint.Add(0, startPoint);
        destinyWayPoint.Add(0, endPoint);

        DistanceMatrixRequest requestDuration = new DistanceMatrixRequest()
        {
            WaypointsOrigin = originWayPoint,
            WaypointsDestination = destinyWayPoint,
            Sensor = false
        };

        DistanceMatrixService distanceService = new DistanceMatrixService();                        
        DistanceMatrixResponse distanceResponse = distanceService.GetResponse(requestDuration);  `
```

I get a REQUEST_DENIED.

Im using:
`GoogleSigned ClienteGoogle = new GoogleSigned("my_api");      
          GoogleSigned.AssignAllServices(ClienteGoogle);`

That its the example from the wiki the one im using, and ive tried using lat/lon and address.

The key its a service key and it have worked finde with Places and Geocoding so its shouldnt be a key problem. Ive seen in some issues that Distance Matrix Api didnt work with GoogleSigned so i tried to not use it but didnt work neither.

Ive done the request and deserialize by myself manually and i get the response OK, so it must be a issue with the class or ToUri method or maybe im forgetting something.

Is there a known problem with the Matrix APi?

**Comment by ericnewton76** [comment]
I believe the Matrix API isn't utilizing the GoogleSigned functionality,
because that was legacy code brought in from way previous.

**Comment by obito1406** [comment]
I manage to make it work(not using others API) but since I would like to use both types of APIs (the ones that required key and the ones that dont) it would be a good implementation on the future to be able to set keys individually per API as others users have suggested before. Meanwhile I will deserialize the calls myself.

**Comment by ericnewton76** [comment]
You can set keys per API, by instead of calling
GoogleSigned.SignAllServices, you'd include the GoogleSigned instance with
the calls.

Unless somebody has committed that away...  I'll check in a while.

**Comment by obito1406** [comment]
That would be great. Let me know if you find out, because ive been searching in the service's class and when making the call to the Api i havent seen the GoogleSigned parameter... Maybe thats not where you are referring to.

**Comment by ericnewton76** [comment]
Of note,  I got rid of having to use a SortedList
