### ISSUE TITLE
Add support for .Net Core

### ISSUE THREAD

**Issue by logankp** [ericnewton76/gmaps-api-net#57]
Hello,

I've started working on porting this project to .Net Core. So far I have the Google.Maps and Google.Maps.Test projects building and all but 2 tests passing (those involving System.Drawing.Color, which hasn't been ported yet).

My fork can be found here: https://github.com/logankp/gmaps-api-net/tree/add-net-core

Let me know if you you would like a pull request for this.

**Comment by logankp** [comment]
All tests now pass! I had to pull in the System.Drawing.Color class from Mono, but it seemed to work. Hopefully in the future this gets integrated into .Net Core so I can remove that ugly hack.

**Comment by Jetski5822** [comment]
+1

**Comment by ericnewton76** [comment]
I was wondering about the System.Drawing issue.  I was considering just setting up something within the project to not need that dependency.

Of note, https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/

Which seems to unify targeting, we might need to just get the details about Net Standard and target that instead of Core.  My guess is that there were too many targets to hit and people couldnt keep up.

Go ahead and create a pull request so we can see the diff easiest.  And thanks for contributing!

**Comment by bangonkali** [comment]
Hi @ericnewton76  Have  you decided to exclude  System.Drawing dependency issue?

**Comment by ericnewton76** [comment]
We could remove the System.Drawing dependency, I remember it only being for
the marker color on the Static Maps portion.

I hate to "rewrite" System.Drawing.Color, maybe somebody can research if
its in the .Net Standard?

**Comment by logankp** [comment]
The last I looked the required classes are still not a part of .Net Core.

**Comment by ericnewton76** [comment]
https://github.com/dotnet/corefx/issues/2315

System.Drawing.Color mentioned here in this issue, I'm still trying to discern whats going to happen with it.  

This is where i envy javascript, where I can define the struct if it doesnt exist or use whatever's already present.

**Comment by ericnewton76** [comment]
So just found this  https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Primitives/src/System/Drawing/Color.cs

which is the .Net Core system.drawing.primitives.color structure

we'll have to add #define statements to keep constrained to .Net core building, and I dont have any build steps that can deal with that.

Of note, build steps a-la nunit v3 could be created to support building multiple outputs of this library

**Comment by logankp** [comment]
Cool! I can take a look at implementing this when I get home. Looks like the System.Drawing.Colors was added just a few weeks after my initial fork.

**Comment by logankp** [comment]
Well apparently it's not as simple as grabbing the latest System.Drawing.Primitives NuGet package, which targets .Net Standard 1.7 (which doesn't even exist yet). Pulling this package in breaks a bunch of dependencies.

May have to wait for the next official NetStandard release.

**Comment by logankp** [comment]
Alright, I got the main project building by upgrading pretty much every package to their pre-release versions, but now the test project can't find the main one because of 1.7 not being a thing yet...

I'm not really sure how to proceed from here besides playing the waiting game :/

**Comment by logankp** [comment]
Some more info on the System.Drawing front: https://blogs.msdn.microsoft.com/dotnet/2017/01/19/net-core-image-processing/

**Comment by ericnewton76** [comment]
Gotcha.  Realistically I've been playing the waiting game with .Net core
because it feels very... without direction... or too many chefs in the
kitchen... or something like that.

**Comment by ericnewton76** [comment]
So I just posted a comment on that blog post, regarindg the color situation.

**Comment by ericnewton76** [comment]
I'm debating for the interim, we could just implement a simple color structure using RGB so that we have something that can be used, then deprecate out once theres a solid .Net Standard color structure that we can use.

**Comment by logankp** [comment]
I'm pretty sure that's what the Mono classes I pulled in were doing, although they're probably much more complex than what is needed. Maybe just strip those down to what is actually being used?

**Comment by logankp** [comment]
With the preview of .Net standard 2.0 released, it seems the System.Drawing.Colors namespace is now supported! I've re-targeted the project for 2.0, removed my Mono color classes and the project builds :)

**Comment by richardthombs** [comment]
@logankp did you update your PR with those changes?

**Comment by logankp** [comment]
@richardthombs Not yet, I forked the wip/netcore branch to continue my work. I'm not sure how the merge strategy is being handled going forward since my initial PR is based on different branch.

**Comment by richardthombs** [comment]
I have a feeling it might be a fairly manual merge! I tried to figure out how big your changes are, but what with the tab/spaces/newline issues and all, it wasn't easy for me to skim through.

Beyond that, I think the trickiest part might be figuring out the build processes. I think @ericnewton76 might have a plan though. I think the async/await pull request might need similar approach.

**Comment by richardthombs** [comment]
PR #105 adds .NET Standard 1.3 support, which I think is good enough for .NET Core support, right?
