### ISSUE TITLE
How do you use this once implemented?

### ISSUE THREAD

**Issue by NoviStudios** [ericnewton76/gmaps-api-net#60]
I used the console inside Visual Studio to install this API, but now I am not sure how to use this. When typing in any code it doesn't seem to recognize any built in functions. Thanks for your help.

**Comment by ericnewton76** [comment]
So you used Nuget to install gmaps-api-net?

If so, the references were added to your project.  If you have many
projects in your solution, check that each project references the nuget
package as well.

Finally, the namespace is Google.Maps, so I would recommend adding a using
Google.Maps; statement in C# or Imports Google.Map in vb.net and you should
be able to utilize the same examples as shown at
https://github.com/ericnewton76/gmaps-api-net/
