### ISSUE TITLE
Elevation service requires https?

### ISSUE THREAD

**Issue by Redeneder** [ericnewton76/gmaps-api-net#61]
I've been trying to get results from the Elevation Service, but did not succeed. I then caught the URI from the service and pasted it in Chrome. The result from Google was: 
"Requests to this API must be over SSL. Load the API with \"https://\" instead of \"http://\." 

I then changed the URI to https and it worked.

I can see that in the ElevationService class both a HttpsUri as a HttpUri are present, but I'm not sure how to use the HttpsUri. It seems HttpUri is default.

**Comment by ericnewton76** [comment]
Google seems to be changing the api to not support http anymore, we'll need
to start just removing the httpuri and making https the default.

If you could, just cut/n/paste this into the issues area for the project?
Thanks for reporting.

E.Newton
