### ISSUE TITLE
Decoding Polylines and adding Markers

### ISSUE THREAD

**Issue by javanmiller** [ericnewton76/gmaps-api-net#68]
I am having trouble with decoding polylines into paths or path.points (not sure which one I need to use) and also with adding Markers. Ultimately, I am trying to grab information from an already provided URL and grabbing the information from that so that I can re-customize the way I want to view my map with other textboxes to change certain things.

Here is what i have so far:
For polylines: (note some code is commented out because i was trying to diagnose it, but am having trouble narrowing it down.
```
 _newPath = _path.Replace("enc:", "")

                    Dim poly = Google.Maps.PolylineEncoder.Decode(_newPath)
                    '  Dim poly As Google.Maps.PolylineEncoder
                    '  Google.Maps.PolylineEncoder.Decode(_newPath)
                    '  Polyline.DecodePolyline(_newPath)
                    '  Polyline.Decode(_newPath)

                    For Each decodedPoint As Google.Maps.PolylineEncoder In poly
                        ' Console.WriteLine(String.Format("Latitude: {0}, Longitude {1}", decodedPoint.Latitude, decodedPoint.Longitude))

                        '   

                        Map.Paths.Add((decodedPoint))   ' Or map.path.points.add ???
                    Next
```

Then for markers i have:
(this actually works, but it is not being pulled from the already provided URL that i previously mentioned, this code is just showing what i know how to do. What i really want to accomplish is to grab all the markers from an already provided URL (string).)
```
Dim _newMarkers As String = "&markers=" & _Markers
                    Dim _Marker As New MapMarkers
                    Dim _NewerMarkers As MapMarkersCollection
                                         For Each MapMarkers As String In _newMarkers

                        Next
                        _Marker.MarkerSize = MarkerSizes.Mid
                        _Marker.Color = ColorTranslator.FromHtml("#" & "44b353")
                        _Marker.Label = "A"
                        _Marker.Locations.Add(New Location("43.626223,-83.890391"))

                        '  _NewerMarkers.Add(_Marker)

                        '_NewerMarkers.Add(_Marker)
                        Map.Markers.Add(_Marker)
```

For right now, I would like to focus on the polylines issue. I think with more tinkering i could eventually figure out the markers ...

**Comment by javanmiller** [comment]
Okay. Well, like I said as for the markers: with more tinkering i could eventually figure out the markers ... and well I did. For your convenience, this is the code I used for the markers:
` Try
                        Dim result As String() = Regex.Split(_Markers, "&markers=") '_Markers.Split(New String("&markers=", StringSplitOptions.None))
                        For Each s As String In result
                            Dim resultresults As String() = s.Split(New String() {"|"}, StringSplitOptions.None)
                            Dim addedMarker As New MapMarkers
                            For Each ss As String In resultresults
                                If ss <> "" Then
                                    Try
                                        If ss.Contains("size") Then
                                            If ss.Contains("mid") Then
                                                addedMarker.MarkerSize = MarkerSizes.Mid
                                            ElseIf ss.Contains("normal") Then
                                                addedMarker.MarkerSize = MarkerSizes.Normal
                                            ElseIf ss.Contains("small") Then
                                                addedMarker.MarkerSize = MarkerSizes.Small
                                            ElseIf ss.Contains("tiny") Then
                                                addedMarker.MarkerSize = MarkerSizes.Tiny
                                            End If
                                        ElseIf ss.Contains("color") Then
                                            Dim color As String = ss.Replace("color:0x", "")
                                            addedMarker.Color = ColorTranslator.FromHtml("#" & color)
                                        ElseIf ss.Contains("label") Then
                                            Dim label As String = ss.Replace("label:", "")
                                            addedMarker.Label = label
                                        Else
                                            addedMarker.Locations.Add(ss)
                                        End If
                                    Catch ex As Exception
                                        MsgBox(ex.ToString)
                                    End Try
                                    Map.Markers.Add(addedMarker)
                                End If
                            Next
                        Next
                    Catch ex As Exception
                        MsgBox(ex.ToString)
                    End Try`


However, I still would like some help with decoding polylines into a path or paths.points, whichever it needs to be (since adding polyline encoded codes do not work directly) Any ideas?

**Comment by javanmiller** [comment]
Well, I figured out a workaround for the paths with polylines. I just combined it from said already provided URL from a map image and combined it with the google map api's URI
This works, but it is not quite using the API's functionality to the fullest. But I am satisfied with it. Though, still, if someone has figured out a way for it to work as I have previously asked, I am welcome to it.


(_newPath is the polyline) (It also includes road thickness in the added URI)
Here it is:
`Dim NewURI As New Uri(Map.ToUri.ToString & "&style=feature:road%7Celement:geometry.fill%7Cweight:" & _RoadWeight & _newPath)
                MapPic.UriSource = NewURI`

**Comment by ericnewton76** [comment]
I'm not sure I follow what you're trying to do here... in the second sample you should be using HttpUtilty.ParseQueryString to separate key=value pairs into a dictionary and so forth, your multi-hierarchy "Contains" checks will fail miserably 

Closing this
