### ISSUE TITLE
Wrong conversion for PlaceType in PlaceRequests

### ISSUE THREAD

**Issue by ergunozyurt** [ericnewton76/gmaps-api-net#74]
Hi,

The only PlaceType conversion for Places API requests is in [PlaceRequest/TypesToUri](https://github.com/ericnewton76/gmaps-api-net/blob/master/src/Google.Maps/Places/PlacesRequest.cs#L104) which doesn't do anything to fit google place types. (https://developers.google.com/places/supported_types)

Google API returns non-filtered results when the given types don't match their types. So, we don't see any error with the request but get wrong result set.

**Comment by richardthombs** [comment]
Hi @ergunozyurt, looking at the code it seems that we might not be not converting `PlaceType` enums  that contain multiple words correctly, but ones with a single word in them should work.

Ie, `PlaceType.AmusementPark` should be converted to `amusement_park`, but currently gets converted to `amusementpark`.

Does that match what you are seeing?

**Comment by ericnewton76** [comment]
Here's a stackoverflow fix for "snake case" (using underscores) 
https://stackoverflow.com/a/30456701/323456

**Comment by ergunozyurt** [comment]
Hi @richardthombs, exactly. 
I'll subscribe notifications of #84 , thanks!
