### ISSUE TITLE
PlacesResponse.NextPageToken and PlacesRequest.PageToken not there.

### ISSUE THREAD

**Issue by bergy6808** [ericnewton76/gmaps-api-net#77]
Google has a way to access next page's results in a places response. I would add this to the PlacesResponse class.

```
                /// <summary>
		/// The token to get the next page, if any.
		/// </summary>
		[JsonProperty("next_page_token")]
		public string NextPageToken { get; set; }
```

And as well, add this to the PlacesRequest class.

```
                /// <summary>
		/// Send the next 20 results from a previous request.
		/// </summary>
		public string PageToken { get; set; }
```

**Comment by khively** [comment]
NearbySearchRequest already has this value. I added it to TextSearchRequest because according to Google Places API it can also have the PageToken. However, the RadarSearch type does not have it. Thus I didn't add it to the base PlacesRequest class.

**Comment by richardthombs** [comment]
@khively thanks for the pull request! @bergy6808 , closing this issue now.
