### ISSUE TITLE
Separate build for .NET v4.5

### ISSUE THREAD

**Issue by richardthombs** [ericnewton76/gmaps-api-net#90]
If we want to retain compatibility with .NET 3.x but also keep moving forwards with adding things like async/await then I think we need to have a separate build for .NET v4.5+

- [ ] How do we configure AppVeyor?
- [ ] How do we get the Visual Studio solution to support this?
- [ ] How do we configure NuGet?

Issues affected by this: #72, #57, #59, #19, #31.

**Comment by ericnewton76** [comment]
I'm wondering if we even need to preserve <v4 compat at this point.

**Comment by ericnewton76** [comment]
AppVeyor supports build matrices so if we need to we can perform multiple builds... might bump into appveyor freemium limits though unless I bring back the psake build 

Visual Studio 2015 i think can work.  We'd just setup conditional compilations, but this gets tricky fast.

Build process would output multiple dlls into nuget convention directories:
- lib/net3.5
- lib/net4.0
- lib/net4.5

However, I think we can probably drop <v4 support at this point

**Comment by richardthombs** [comment]
Jumping to 1.6 sounds good to me, but if I'm reading [this](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-platforms-support) correctly then folks wouldn't be able to build UWP programs with it, which might be a problem?

**Comment by richardthombs** [comment]
How about we start by updating our minimum framework version from 3.5 -> 4.61? That will at least pave the way for us to add async/await.

**Comment by richardthombs** [comment]
Seems like this is not an issue anymore as we're targeting .NET 4.61 as the minimum framework.
